### PR TITLE
Actually add a link to wikipedia here

### PR DESCRIPTION
**Pull request by mquinson**
# Description
This is just a tiny little improvement of the exercise text. No test were done, but I don't think this mandates any.

### CODE REVIEW

**Comment by raphendyr** [comment]
Can you use a different format for the link:

```rst
see `standard streams`_ on Wikipedia) from the programs it

.. _standard streams: https://en.wikipedia.org/wiki/Standard_streams
```

In addition, can you change the commit title to `Add a link to Wikipedia`. E.g. "here" isn't very informative in a git commit message.

**Comment by mquinson** [comment]
Hello, I did not checkout and create a branch, but edited directly in the web interface. The downside is that I cannot edit my commit. I would have to close this issue and open a new one. Given the change, it may be easier if you do it yourself?

Sorry,

**Comment by markkuriekkinen** [comment]
I made a new commit with the changes suggested by Jaakko: https://github.com/apluslms/course-templates/commit/cb8478fa7e07e3ef736e4c29ce80d9ea170fd1e7

It is in the master branch now. Thank you for the small contribution :+1:

**Comment by mquinson** [comment]
Thanks a lot to you guys, this is a very appealing projet.

**Pull request closed without merging**
